# Meta data
baseURL: "https://example.org/"

defaultContentLanguage: ru
languages:
  en:
    disabled: false
    contentDir: content/en
    params:
      # General info
      description: "Notes and stuff by @tembeon"
      keywords: [Blog, Development, tem_notes]

      # Info on homepage
      homeInfoParams:
        Title: Welcome to tem [notes]
        Content: "Notes and stuff by [@tembeon](https://t.me/tembeon)"
      socialIcons:
        - name: "other"
          title: "My Telegram channel"
          url: "https://t.me/tembeon_notes"
        - name: "telegram"
          title: "Contact me on Telegram"
          url: "https://t.me/tembeon"

      # Miscellaneous
      editPost:
        Text: "Suggest changes"

  ru:
    disabled: false
    contentDir: content/ru
    params:
      # Основные сведения
      description: "Заметки и прочее от [@tembeon](https://t.me/tembeon)"
      keywords: [Блог, Разработка, tem_notes]

      # Информация на главной
      homeInfoParams:
        Title: Добро пожаловать в tem [notes]
        Content: "Заметки и прочее от [@tembeon](https://t.me/tembeon)"
      socialIcons:
        - name: "other"
          title: "Мой канал в Telegram"
          url: "https://t.me/tembeon_notes"
        - name: "telegram"
          title: "Связаться в Telegram"
          url: "https://t.me/tembeon"

      # Прочее
      editPost:
        Text: "Предложить изменения"

title: "tem [notes]"
theme: PaperMod

# Site config
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "tem [notes]"
  author: "Tembeon"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  # Post settings
  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true

  editPost:
    URL: "https://github.com/Tembeon/tem_notes/content"
    appendFilePath: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: false
    codeFences: true
    # guessSyntax: true
    lineNos: true
    style: github-dark

  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1