# Meta data
baseURL: "https://binarycascade.dev/"

defaultContentLanguage: ru
languages:
  en:
    disabled: false
    contentDir: content/en
    params:
      # General info
      description: "Notes and stuff by BinaryCascade team"
      keywords: [ Blog, Development, BinaryCascade ]

      # Info on homepage
      homeInfoParams:
        Title: "Welcome to BinaryCascade blog"
        Content: "Notes and stuff by BinaryCascade team"
      socialIcons:
        - name: "github"
          title: "Our GitHub"
          url: "https://github.com/BinaryCascade"

      # Miscellaneous
      editPost:
        Text: "Suggest changes"

  ru:
    disabled: false
    contentDir: content/ru
    params:
      # Основные сведения
      description: "Заметки и прочее от BinaryCascade"
      keywords: [ Блог, Разработка, BinaryCascade ]

      # Информация на главной
      homeInfoParams:
        Title: "Добро пожаловать в блог BinaryCascade"
        Content: "Заметки и прочее от BinaryCascade"
      socialIcons:
        - name: "other"
          title: "@tembeon канал в Telegram"
          url: "https://t.me/tembeon_notes"

      # Прочее
      editPost:
        Text: "Предложить изменения"

title: "BinaryCascade blog"
theme: PaperMod

# Site config
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "BinaryCascade blog"
  author: "BinaryCascade team"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  # Post settings
  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true

  editPost:
    URL: "https://github.com/BinaryCascade/blog/content"
    appendFilePath: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: [ "title", "permalink", "summary", "content" ]

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: false
    codeFences: true
    # guessSyntax: true
    lineNos: true
    style: github-dark

  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
